#include "IDD_PROPPAGE_COLORS_WINMERGE.h"
#include "ui_IDD_PROPPAGE_COLORS_WINMERGE.h"
IDD_PROPPAGE_COLORS_WINMERGE::IDD_PROPPAGE_COLORS_WINMERGE(QWidget *parent) :
	QDialog(parent),
	ui(new Ui::IDD_PROPPAGE_COLORS_WINMERGE)
{
	ui->setupUi(this);
}
IDD_PROPPAGE_COLORS_WINMERGE::~IDD_PROPPAGE_COLORS_WINMERGE()
{
	delete ui;
}
void IDD_PROPPAGE_COLORS_WINMERGE::on_pushButton_clicked()
{
}
